Create Icons
TiendaNube/nimbus-icons pull request #43
Opened 2022-09-21 14:22 UTC by LucasBayley

2022-09-22 20:15 UTC, juniorconquista approved these changes

2022-09-23 13:05 UTC, gabifagundes approved these changes

2022-09-23 15:03 UTC, juanchigallego requested changes
Muy buenos!
Una cosa que me quedé pensando @LucasBayley es en los nombres. Trataría de pensar unos más genéricos, para no asociar tanto a los iconos con la función que les queremos dar en el proyecto en el que los vamos a utilizar.
Te paso unas sugerencias pero decime qué pensas:
- `Cores` podría ser `Color palette` o `Palette`
- `QR Code` está perfecto ✅
- `SEO Search` puede funcionar, pero tal vez podríamos ponerle algo más por el lado de `Browser search` o algo similar. Se me ocurren otros usos que no estén directamente vinculados con el SEO.
- `Section` puede ser 🤔 pero me quedo pensando si tiene otras aplicaciones que no tienen que ver con secciones. Tal vez un nombre más genérico como `Vertical stacks` pueda servir.

Qué te parece? 🙂

2022-09-23 19:52 UTC, LucasBayley commented
@juanchigallego Muchas gracias por la devolución!

Estoy de acuerdo con "Color Palette" y "Browser Search" como cambio.
Para Section quiero pensar bien si vertical stacks u otra alternativa pueda ir, muchas gracias!

2022-09-27 15:21 UTC, LucasBayley commented
Olá! Compartilho com vocês um redesign que fiz para o QR Code, acreditamos que este último design pode ser ainda mais claro. Por outro lado, já modifiquei os nomes de acordo com o retorno, obrigado!

![QR-CODE](https://user-images.githubusercontent.com/110427741/192551771-6b8f72bd-8654-49f1-9d89-1171fde6a1dd.jpg)

2022-10-14 00:56 UTC, LucasBayley commented
The icons were updated as well as their names

2022-10-14 11:30 UTC, marcospaiva commented
@LucasBayley Hi Luqui. Estuve vendo los SVGs nuevos y tienen pequeños issues con los paths. 

Mirá como esta los paths del Collor Palette. 

<img width="634" alt="Screen Shot 2022-10-14 at 08 29 05" src="https://user-images.githubusercontent.com/14277806/195836516-df9e1a8f-dc14-4000-92ec-24bd4479351d.png">

Yo CREO que puede ser por el tema de estar generado por Illustrator. Podes intentar generar por Figma?

2022-10-14 14:06 UTC, LucasBayley commented
Hola @marcospaiva Muchas gracias por el aviso, efectivamente Ilustrator estaba exportando mal los iconos. Ya está resuelto!

@juanchigallego Cuando puedas me dices si está ok para aprobar, muchas gracias!

2022-10-14 17:19 UTC, juanchigallego commented
Hola @LucasBayley ! Cómo va?

Revisando el PR veo que quedaron las versiones viejas de los archivos en la librería:
<img width="200" alt="Captura de Pantalla 2022-10-14 a la(s) 14 15 43" src="https://user-images.githubusercontent.com/25963096/195904428-273d4c01-1e97-415a-ac61-be1216de8933.png">

Aprovechando, otra cosa que sería bueno es estandarizar los nombres de los archivos usando sólo `lowercase` y separando las palabras por guiones en vez de espacios (`qr-code` en vez de `QR Code`).

Una última cosa, antes de hacer push, te aconsejo correr el comando `yarn svgo` que hace una limpieza de los archivos svg, eliminando todas las propiedades innecesarias y reduciendo considerablemente el tamaño. (Sé que esto no está en la documentación del repo 😅 ya lo vamos a agregar! Pero te lo comento así lo tenés en cuenta!).

Avisame si hay alguna duda o escribime por slack sin problema!

2022-10-18 13:01 UTC, LucasBayley commented
Hola @juanchigallego  Dejo constancia por acá de las modificaciones en los iconos, muchas gracias!

2022-10-24 20:13 UTC, marcospaiva approved these changes

2022-10-27 14:24 UTC, juanchigallego approved these changes

2022-10-27 14:25 UTC, merged